
version: 2

formats: [htmlzip]

python:
  system_packages: true
  version: 3.7
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false


