# -*- coding: utf-8 -*-
#
# EnsembleMD Tutorial documentation build configuration file, created by
# sphinx-quickstart on Mon Aug 31 12:44:39 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import shlex
import urllib2
import radical.utils as ru

script_dir = os.path.dirname(os.path.realpath(__file__))

################################################################################
##
print "* Generating resource configuration docs: resources.rst"

try:
    os.remove("{0}/resources.rst".format(script_dir))
except OSError:
    pass

try:
    os.mkdir('resource_list')
except OSError:
    pass

with open("{0}/resources.rst".format(script_dir), "w") as resources_rst:

    resources_rst.write("""
.. _chapter_resources:

List of Pre-Configured Resources
================================


""")

    resource_list = [ 
  "resource_das4.json",
  "resource_epsrc.json",
  "resource_futuregrid.json",
  "resource_iu.json",
  "resource_local.json",
  "resource_lrz.json",
  "resource_ncar.json",
  "resource_ncsa.json",
  "resource_nersc.json",
  "resource_ornl.json",
  "resource_radical.json",
  "resource_rice.json",
  "resource_stfc.json",
  "resource_xsede.json"]

    for res in resource_list:
      response = urllib2.urlopen('https://raw.githubusercontent.com/radical-cybertools/radical.pilot/devel/src/radical/pilot/configs/%s'%res)
      html = response.read()
      with open('resource_list/'+res,'w') as f:
        f.write(html)
      f.close()
    import glob
    configs = glob.glob("resource_list/resource_*.json" )
    for config in configs:

        if not config.endswith(".json"):
            continue # skip all non-python files

        if "/resource_aliases" in config:
            continue # skip alias files

        print " * %s" % config

        try: 
             json_data = ru.read_json_str(config)
        except Exception, ex:
             print "    * JSON PARSING ERROR: %s" % str(ex)
             continue

        config = config.split('/')[-1]

        resources_rst.write("{0}\n".format(config[:-5].upper()))
        resources_rst.write("{0}\n\n".format("-"*len(config[:-5])))

        for host_key, resource_config in json_data.iteritems():
            resource_key = "%s.%s" % (config[:-5], host_key)
            print "   * %s" % resource_key
            try:
                default_queue = resource_config["default_queue"]
            except Exception, ex:
                default_queue = None

            try:
                working_dir = resource_config["default_remote_workdir"]
            except Exception, ex:
                working_dir = "$HOME"

            try:
                python_interpreter = resource_config["python_interpreter"]
            except Exception, ex:
                python_interpreter = None

            try:
                access_schemas = resource_config["schemas"]
            except Exception, ex:
                access_schemas = ['n/a']

            resources_rst.write("{0}\n".format(host_key.upper()))
            resources_rst.write("{0}\n\n".format("*"*len(host_key)))
            resources_rst.write("{0}\n\n".format(resource_config["description"]))
            resources_rst.write("* **Resource label**      : ``{0}``\n".format(resource_key[9:]))
            resources_rst.write("* **Raw config**          : :download:`{0} <../../src/radical/pilot/configs/{0}>`\n".format(config))
            if resource_config["notes"] != "None":
                resources_rst.write("* **Note**            : {0}\n".format(resource_config["notes"]))
            resources_rst.write("* **Default values** for ComputePilotDescription attributes:\n\n")
            resources_rst.write(" * ``queue         : {0}``\n".format(default_queue))
            resources_rst.write(" * ``sandbox       : {0}``\n".format(working_dir))
            resources_rst.write(" * ``access_schema : {0}``\n\n".format(access_schemas[0]))
            resources_rst.write("* **Available schemas**   : ``{0}``\n".format(', '.join(access_schemas)))
            resources_rst.write("\n")

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../../'))
#sys.path.insert(0, os.path.abspath('../src/radical/ensemblemd'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
   'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'radical.ensemblemd'
copyright = u'2015, The Radical Group at Rutgers University'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
#version = open("{0}/../src/radical/ensemblemd/VERSION".format(script_dir), "r").readline()
# rst_epilog = '.. |VERSION| replace:: %s' % version



# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', '_themes']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------
html_use_smartypants = True

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'armstrong'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
"collapsiblesidebar" : "true",
}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ["_themes", ]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'radical.ensemblemd.doc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',

# Latex figure (float) alignment
#'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'radicalensemblemd.tex', u'radical.ensemblemd Documentation',
   u'The Radical Group at Rutgers University', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'radicalensemblemd', u'radical.ensemblemd Documentation',
     [u'The Radical Group at Rutgers University'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'radicalensemblemd', u'radical.ensemblemd Documentation',
   u'The Radical Group at Rutgers University', 'radicalensemblemd', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False
